import { AssumptionEntry } from './assumptions.types';

export const ASSUMPTIONS_REGISTRY: readonly AssumptionEntry[] = [
  {
    id: 'opwek-solar-flh-2025',
    theme: 'opwek',
    title: 'Zon full-load-hours 2025',
    assumption: 'Voor zon wordt standaard gerekend met 949 full-load-hours in 2025.',
    formula: 'jaaropwek (TWh) = vermogen (GW) x full-load-hours / 1000',
    source: 'Historische 2025-reeks in app-config, afgeleid uit gebruikte datasetkalibratie.',
    impact: 'Hogere full-load-hours verhogen de jaaropwek van zon en verlagen netto tekorturen.',
    criticalNote: 'Bij uitzonderlijke instralingsjaren kan deze waarde te optimistisch of te conservatief uitpakken.',
    isAdjustable: true,
    adjustableVia: 'Instelbare zonnecapaciteit en modelinstellingen voor opwek.',
    tags: ['zon', 'full-load-hours', 'capaciteitsfactor', 'opwek'],
  },
  {
    id: 'opwek-windland-flh-2025',
    theme: 'opwek',
    title: 'Wind op land full-load-hours 2025',
    assumption: 'Voor wind op land wordt standaard 2390 full-load-hours gebruikt.',
    formula: 'jaaropwek (TWh) = vermogen (GW) x full-load-hours / 1000',
    source: 'Kalibratie in configuratie op basis van gebruikte jaarreeks voor 2025.',
    impact: 'Stuurt direct de jaarlijkse windland-opwek en daarmee batterijbehoefte en curtailment.',
    criticalNote: 'Regionale windschommelingen en netbeperkingen zitten niet expliciet in deze vaste factor.',
    isAdjustable: true,
    adjustableVia: 'Instelbare windlandcapaciteit in balans/opwek-instellingen.',
    tags: ['windland', 'full-load-hours', 'opwek'],
  },
  {
    id: 'balans-nuclear-min-share',
    theme: 'balans',
    title: 'Kernenergie minimale output',
    assumption: 'Kernvermogen wordt in de curtailmentlogica niet onder 50% teruggeregeld.',
    formula: 'kern-minimum = kernprofiel x 0,5',
    source: 'Hardcoded modelregel in de balanssimulatie.',
    impact: 'Vergroot kans op curtailment van andere bronnen bij overschoturen.',
    criticalNote: 'Deze regel kan te stug zijn als toekomstige kerncentrales flexibeler kunnen draaien.',
    isAdjustable: false,
    tags: ['kernenergie', 'curtailment', 'minimum output'],
  },
  {
    id: 'balans-private-winter-reserve',
    theme: 'balans',
    title: 'Dynamische private reserve (14 dagen + 20% buffer)',
    assumption: 'De private batterij gebruikt één uniforme strategie met een 14-daags vooruitvenster en achterwaartse tekortopbouw, met een zachte ondergrens van 20% SoC.',
    formula: 'target SoC(h) = max(0,2 x private capaciteit, required SoC(h)); required SoC(h) uit achterwaartse tekortopbouw in 14-daags venster',
    source: 'Hardcoded 14-daagse backcast met 20%-buffer in de balanssimulatie.',
    impact: 'Stuurt opslag naar verwachte tekorturen, maar voorkomt dat de private batterij in normale uren te snel tot 0% wordt leeggetrokken.',
    criticalNote: 'Door de 20%-buffer blijft extra veiligheid aanwezig; in noodsituaties kan deze buffer alsnog worden aangesproken.',
    isAdjustable: false,
    tags: ['private batterij', 'dynamische reserve', '14 dagen', '20%', 'soc'],
  },
  {
    id: 'balans-private-grid-limit',
    theme: 'balans',
    title: 'Maximale private netafname',
    assumption: 'Private vraag plus publiek->private laadstroom wordt begrensd door een max-load instelling.',
    formula: 'private netgebruik per uur <= privateGridMaxLoadGW x 1.000.000 kWh',
    source: 'Modelinput uit balansinstellingen, standaard 35 GW.',
    impact: 'Beperkt hoe snel private tekorten en reserve-aanvulling via publiek net kunnen worden afgevangen.',
    criticalNote: 'Eenzelfde landelijke grens voor alle uren is simplistisch ten opzichte van echte netcongestie.',
    isAdjustable: true,
    adjustableVia: 'Balans-instelling private net max load (GW).',
    tags: ['netlimiet', 'private vraag', 'balans'],
  },
  {
    id: 'balans-transport-ev-efficiency-factor',
    theme: 'balans',
    title: 'Vervoer: EV-efficiencyfactor 3,75',
    assumption: 'Niet-elektrisch vervoer uit CBS/NOVE wordt omgerekend naar elektrisch verbruik met factor 3,75 omdat EV\'s veel efficiënter zijn dan verbranding.',
    formula: 'elektrische vervoersvraag = fossiele eindenergie vervoer / 3,75',
    source: 'Projectaanname op basis van vergelijking km per liter benzine versus km per kWh bij moderne auto\'s.',
    impact: 'Deze factor bepaalt rechtstreeks de omvang van de vervoers-kWh in de totale vraagcurve.',
    criticalNote: 'Factor 3,75 is een middenaanname: zwaar vervoer kan lager uitvallen, terwijl vervanging van oudere voertuigen door moderne EV\'s juist richting factor 4 of hoger kan bewegen.',
    isAdjustable: false,
    tags: ['vervoer', 'ev', 'efficiency', '3.75', 'cbs', 'nove'],
  },
  {
    id: 'balans-v2g-not-modeled',
    theme: 'balans',
    title: 'Vehicle-to-Grid (V2G) is nu niet gemodelleerd',
    assumption: 'Het huidige model rekent geen expliciete V2G-aansturing of bidirectioneel laden van auto\'s naar het net door.',
    formula: 'n.v.t. in huidige simulatie (V2G-teruglevering = 0 in model)',
    source: 'Modelscope van de huidige versie; V2G-logica ontbreekt nog in dispatchregels. Potentie-inschatting 2025 gebaseerd op RDW Open Data (dataset m9d7-ebf2, categorieen M1/N1/N2+N3).',
    impact: 'Voor jaarverbruik verandert V2G weinig, maar voor netbelasting en piekverdeling kan de impact groot zijn.',
    criticalNote: 'Voor 2025 geeft een afgeronde inschatting: alleen personenauto\'s 10,8 mln x 100 kWh = 1,08 TWh. Inclusief bestelauto\'s en vrachtauto\'s: (10,8 mln x 100) + (1,3 mln x 100) + (231,6k x 500) = circa 1,33 TWh. Praktisch inzetbaar deel blijft lager door beschikbaarheid, gebruikersgedrag, degradatie en contractprikkels.',
    isAdjustable: false,
    tags: ['v2g', 'vehicle-to-grid', 'auto batterij', '100 kwh', '1.08 twh', '1.33 twh', 'rdw 2025', 'netbelasting'],
  },
  {
    id: 'kosten-household-share',
    theme: 'kosten',
    title: 'Huishouden aandeel in verbruik',
    assumption: 'Huishoudens nemen 35% van totaal elektriciteitsverbruik voor kostenallocatie.',
    formula: 'huishouddeel = totale kosten x 0,35',
    source: 'CBS-gedreven aanname in kostenmodel.',
    impact: 'Verdeelt infrastructuur- en batterijgerelateerde kosten tussen huishoudens en bedrijven.',
    criticalNote: 'Een vaste 35%-split kan afwijken bij elektrificatieversnelling in industrie of mobiliteit.',
    isAdjustable: false,
    tags: ['kostenverdeling', 'huishoudens', 'bedrijven'],
  },
  {
    id: 'kosten-household-variable-price',
    theme: 'kosten',
    title: 'Huishoudelijke afnameprijs (ct/kWh)',
    assumption: 'Huishoudprijs combineert opwekkosten, EB en 21% BTW over die componenten.',
    formula: 'ct/kWh = (ct opwek + 12,599 ct EB) x 1,21',
    source: 'Kostenservice op basis van energy-tax en BTW-constanten.',
    impact: 'Stuurt de maandelijkse afnamekosten per huishoudaansluiting in de berekeningen-tab.',
    criticalNote: 'Netbeheerderstarieven, leveringscontracten en staffels buiten model kunnen uitkomst sterk wijzigen.',
    isAdjustable: true,
    adjustableVia: 'Opwekkosten indirect via technologiekosten; belastingconstanten zijn hardcoded.',
    tags: ['afname', 'eb', 'btw', 'ct/kWh', 'huishouden'],
  },
  {
    id: 'kosten-aansluitingen-nl',
    theme: 'kosten',
    title: 'Aantallen aansluitingen NL',
    assumption: 'Kosten per aansluiting gebruiken 8,2 mln huishoudens en 800k bedrijfsaansluitingen.',
    formula: 'maandkosten per aansluiting = jaarkosten / aantal aansluitingen / 12',
    source: 'CBS-gebaseerde vaste parameterwaarden in het kostenmodel.',
    impact: 'Direct effect op euro per maand per aansluiting in de kostenkaarten.',
    criticalNote: 'Als aantallen of definities van aansluitingen veranderen, schuiven maandbedragen mee.',
    isAdjustable: false,
    tags: ['aansluitingen', 'maandkosten', 'kosten'],
  },
  {
    id: 'kosten-battery-cell-price-default',
    theme: 'kosten',
    title: 'Batterij celprijs: 40 EUR/kWh referentie naar 20 EUR/kWh modelwaarde',
    assumption: 'Uitgangspunt is circa 40 EUR/kWh consumentenprijs voor MB56 628Ah-cellen; de modelwaarde 20 EUR/kWh representeert verwachte bulkinkoop plus opschaling naar grotere cellen (4 kWh per cel).',
    formula: 'celcapex = energiecapaciteit (kWh) x model-celprijs; model-celprijs start op 20 EUR/kWh als afgeleide scenario-aanname van 40 EUR/kWh consumentenreferentie',
    source: 'Domeinaanname voor dit project: consumentenreferentie 40 EUR/kWh, met verwachte daling bij grote afname en grotere celgrootte.',
    impact: 'De gekozen model-celprijs heeft groot effect op totale opslagkosten en daarmee op systeemkost in de berekeningen.',
    criticalNote: 'Dit blijft een scenario-aanname: marktprijzen kunnen afwijken door chemie, leverancier, contractvorm, timing en volume.',
    isAdjustable: true,
    adjustableVia: 'Kosten-tab → Batterij kostmodel → Celprijs',
    tags: ['batterij', 'celprijs', '40 eur/kwh', '20 eur/kwh', 'mb56 628ah', 'bulkprijs', '4 kwh cel', 'opslag', 'kosten'],
  },
  {
    id: 'waterstof-vraag-pj',
    theme: 'waterstof',
    title: 'Vaste niet-elektrische waterstofvraag',
    assumption: 'Waterstofimportvraag is opgebouwd uit drie vaste PJ-componenten op basis van CBS 2024.',
    formula: 'totale vraag (PJ) = bunkering + nijverheid + niet-energetisch gebruik',
    source: 'Handmatig vastgezette waarden in de waterstof-importstore.',
    impact: 'Bepaalt direct de jaarlijkse importvraag en variabele importkosten.',
    criticalNote: 'Vaste vraag zonder scenario-elasticiteit kan toekomstige efficiency- of substitutie-effecten missen.',
    isAdjustable: false,
    tags: ['waterstof', 'import', 'pj', 'cbs'],
  },
  {
    id: 'waterstof-kwh-per-kg',
    theme: 'waterstof',
    title: 'Energie-inhoud waterstof (LHV)',
    assumption: 'Conversie van EUR/kg naar EUR/kWh gebruikt 33,33 kWh per kg (LHV).',
    formula: 'EUR/kWh = EUR/kg / 33,33',
    source: 'Constante in waterstof-importstore.',
    impact: 'Bepaalt de afgeleide kWh-prijs en daarmee importkosten per jaar.',
    criticalNote: 'Andere definities (HHV, ketenefficiency, opslagverliezen) geven andere effectieve kosten.',
    isAdjustable: false,
    tags: ['lhv', 'eur/kg', 'eur/kwh', 'waterstof'],
  },
  {
    id: 'kritisch-2050-nulmeting',
    theme: 'kritisch',
    title: '2050 is een nulmeting, geen exacte voorspelling',
    assumption: 'De site gebruikt een 2050-referentiescenario als nulmeting en rekent niet alle toekomstverwachtingen expliciet door.',
    formula: 'n.v.t. (referentiekader voor scenariovergelijking)',
    source: 'Modelontwerp: beperk schijnnauwkeurigheid bij sterk onzekere toekomstfactoren.',
    impact: 'Uitkomsten zijn vooral richtinggevend voor vergelijking tussen scenario\'s.',
    criticalNote: 'Factoren zoals bevolkingsgroei, datacenters, efficiencywinst, verplaatsing van zware industrie, autodelen/autonoom vervoer, isolatie, betere batterijen en hoger PV-rendement kunnen zowel plus als min uitwerken.',
    isAdjustable: false,
    tags: ['nulmeting', '2050', 'referentie', 'onzekerheid', 'scenario'],
  },
  {
    id: 'kritisch-modelscope',
    theme: 'kritisch',
    title: 'Model is systeemindicatie, geen marktsimulatie',
    assumption: 'Het model rekent fysieke en kosttechnische orde-grootte op uurprofielen, niet volledige marktwerking.',
    formula: 'n.v.t.',
    source: 'Ontwerpkeuze van de apparchitectuur met beperkte set stuurvariabelen.',
    impact: 'Uitkomsten zijn richtinggevend voor scenariovergelijking, niet direct tarief- of investeringsadvies.',
    criticalNote: 'Gebruik resultaten samen met gevoeligheidsanalyse en externe validatie.',
    isAdjustable: false,
    tags: ['beperking', 'onzekerheid', 'scenario'],
  },
];
