import { FaqEntry, GlobalPictureItem } from './assumptions.types';

export const GLOBAL_PICTURE_ITEMS: readonly GlobalPictureItem[] = [
  {
    id: 'scope',
    title: 'Wat dit model wel en niet doet',
    summary: 'Het model gebruikt een 2050-nulmeting als referentie en vergelijkt scenario\'s op basis van uurprofielen, kostencomponenten en beleidskeuzes.',
    whyItMatters: 'Gebruik de uitkomsten als richting voor discussie en scenariovergelijking, niet als exact marktvoorspelmodel.',
  },
  {
    id: 'cost-interpretation',
    title: 'Kosten zijn opgebouwd uit componenten',
    summary: 'Veel prijzen zijn opgebouwd uit meerdere blokken, zoals cellen, power electronics, beheer, infrastructuur en belastingen.',
    whyItMatters: 'Een modelwaarde zoals 20 EUR/kWh voor cellen (afgeleid van hogere consumentenreferentie met bulkdaling) is niet hetzelfde als totale systeemkosten voor opslag.',
  },
  {
    id: 'uncertainty',
    title: 'Onzekerheid is expliciet onderdeel van de uitkomst',
    summary: 'Aannames over full-load-hours, reservegrenzen, netlimieten en vraagontwikkeling hebben grote invloed op de resultaten.',
    whyItMatters: 'Bij discussies over optimisme of pessimisme moet je juist deze aannames naast elkaar vergelijken.',
  },
];

export const FAQ_ENTRIES: readonly FaqEntry[] = [
  {
    id: 'faq-battery-cell-price',
    question: 'Waarom rekent de website met 20 EUR/kWh voor batterijcellen?',
    shortAnswer: '40 EUR/kWh is de consumentenreferentie; 20 EUR/kWh is in dit model een afgeleide scenario-waarde voor bulkinkoop en grotere cellen.',
    detailedAnswer: 'Het uitgangspunt is circa 40 EUR/kWh voor MB56 628Ah in consumentencontext. De modelwaarde 20 EUR/kWh representeert verwachte daling bij grote afname plus opschaling naar 4 kWh per cel. Daarnaast bestaat de totale batterijprijs uit meer dan cellen alleen: ook power electronics, beheer/BMS, hallen, rente en OPEX.',
    relatedAssumptionIds: ['kosten-battery-cell-price-default'],
    tags: ['batterij', 'celprijs', '40 eur/kwh', '20 eur/kwh', 'mb56 628ah', 'bulk', '4 kwh', 'kosten'],
  },
  {
    id: 'faq-winter-reserve',
    question: 'Waarom gebruikt de private batterij nu een dynamische reserve',
    shortAnswer: 'Omdat de simulatie nu per uur met een 14-daags venster bepaalt hoeveel private opslag nodig is om toekomstige tekorturen op te vangen.',
    detailedAnswer: 'Per uur kijkt het model 14 dagen vooruit en rekent daarna achterwaarts hoeveel SoC nodig is. Daardoor wordt opslag gestuurd op verwachte tekorten in plaats van op vaste kalendermaanden.',
    relatedAssumptionIds: ['balans-private-winter-reserve'],
    tags: ['dynamische reserve', '14 dagen', 'soc', 'balans'],
  },
  {
    id: 'faq-private-grid-limit',
    question: 'Wat betekent de private netlimiet van 35 GW?',
    shortAnswer: 'Die limiet begrenst per uur de som van private afname en publiek-naar-privaat laden.',
    detailedAnswer: 'De limiet is bedoeld om te voorkomen dat de private kant onbeperkt op het publieke net leunt. Dit is een vereenvoudiging van echte netcongestie en daarom vooral nuttig als scenario-instelling, niet als exact netwerkmodel.',
    relatedAssumptionIds: ['balans-private-grid-limit'],
    tags: ['netlimiet', '35 gw', 'balans'],
  },
  {
    id: 'faq-household-price',
    question: 'Waarom is de huishoudelijke prijs geen puur marktgetal?',
    shortAnswer: 'De huishoudelijke prijs combineert model-opwekkosten met energiebelasting en BTW.',
    detailedAnswer: 'In deze app is de huishoudelijke afnameprijs een rekenkundige samenstelling van opwekcomponenten plus fiscale componenten. Contractvormen, leveranciersmarges en individuele tariefstructuren zijn niet volledig gemodelleerd.',
    relatedAssumptionIds: ['kosten-household-variable-price'],
    tags: ['huishouden', 'eb', 'btw', 'ct/kwh'],
  },
  {
    id: 'faq-offshore-existing-connection-costs',
    question: 'Waarom tellen de eerste 4,75 GW zeeverbindingen niet mee als nieuwe infrastructuurkosten?',
    shortAnswer: 'Omdat die 4,75 GW als reeds bestaande aanlandingsinfrastructuur is behandeld; alleen extra capaciteit boven 4,75 GW krijgt nieuwe TenneT-infrakosten in het model.',
    detailedAnswer: 'In de kostenmodule worden offshore-aanlandingssystemen alleen gerekend voor uitbreiding boven de bestaande 4,75 GW. Daardoor voorkom je dat historische of al geplande basisinfrastructuur dubbel in nieuwe scenariokosten terugkomt.',
    detailedBullets: [
      'Drempel in het model: de eerste 4,75 GW wind op zee telt als bestaand.',
      'Nieuwe infrakosten starten pas bij capaciteit boven 4,75 GW.',
      'Extra capaciteit wordt omgezet naar 2 GW TenneT-systemen met afronding naar boven (ceil).',
      'Praktisch: bij 4,75 GW of lager is de extra aanlandingspost 0 GW in de kostenrij.',
    ],
    relatedAssumptionIds: ['kosten-household-share', 'kosten-household-variable-price'],
    tags: ['wind op zee', 'aanlanding', 'tennet', 'infrastructuur', '4.75 gw', 'kosten'],
  },
  {
    id: 'faq-hydrogen-target-mode',
    question: 'Hoe werkt waterstofproductie met een TWh-doel per jaar?',
    shortAnswer: 'Je voert een gewenst waterstof-outputdoel (TWh/jaar) en elektrolyserrendement (%) in. Het model rekent dit om naar benodigde stroominput als referentie en gebruikt die voor transparantie in de UI.',
    detailedAnswer: 'De waterstofinstelling is referentiegestuurd: je vult output + rendement in, waarna het model de benodigde elektriciteit bepaalt met stroominput = output / rendement. Zodra waterstof actief is (doel > 0), gaat resterend overschot na de normale dispatchvolgorde naar elektrolyse.',
    detailedBullets: [
      '0 TWh output betekent: geen waterstofdoel, dus geen omzetting van overschot naar waterstof.',
      'Rekenregel: benodigde stroominput (TWh) = gewenste waterstof-output (TWh) / (rendement/100).',
      'Bij een positief doel gaat eerst de gewone elektriciteitsvraag voor; alleen resterend overschot kan naar waterstof.',
      'PV-naar-waterstof is begrensd op maximaal 35 GW per uur.',
      'Niet-PV overschotten (zoals wind of kern-curtailment) gaan volledig naar waterstof zolang er overschot is.',
      'De berekende stroominput werkt als referentie/KPI; het model kapt waterstofproductie niet hard af op dit jaargetal.',
      'Als er in het jaar te weinig overschot beschikbaar is, wordt het outputdoel niet volledig gehaald; als er veel overschot is, kan productie boven het doel uitkomen.',
    ],
    relatedAssumptionIds: ['kritisch-modelscope', 'kritisch-2050-nulmeting'],
    tags: ['waterstof', 'twh doel', 'jaardoel', 'curtailment', '35 gw', 'overschot'],
  },
  {
    id: 'faq-heat-demand',
    question: 'Hoe is de warmtevraag bepaald?',
    shortAnswer: 'De warmtevraag is afgeleid uit gasvraag en omgerekend naar elektrische warmtevraag met een rendement van 90% en een warmtepompfactor 3.',
    detailedAnswer: 'De warmtevraag in dit model is een omzetting van gas naar elektriciteitsvraag voor warmte. De rekensom is: warmtevraag = gasvraag x 0,9 / 3. De 0,9 staat voor een gasketelrendement van 90%: ongeveer 10% van de energie gaat verloren via rookgas en andere verliezen. Dat HR-ketels een rendement boven 100% lijken te hebben, betekent niet dat ze meer warmte uit het gas halen dan er fysisch in zit; ze halen extra bruikbare warmte uit de waterdamp in de rookgassen door condensatie van de waterdamp, waardoor het rendement ten opzichte van de onderwaarde van aardgas hoger dan 100% kan lijken. Voor de warmtepomp gebruiken we factor 3 juist omdat de winter het echte probleem is: warmtepompen zijn dan minder efficiënt en de piekvraag valt samen met de koudste uren. Naast ruimteverwarming zit in deze gasvraag ook aardgas voor industrieel gebruik; dat deel is kleiner, maar we houden voor de omzetting dezelfde factor aan vanwege efficiencyverbeteringen in het hele warmtevraagbeeld.',
    detailedBullets: [
      'Formule: warmtevraag = gasvraag x 0,9 / 3.',
      '0,9 = 90% ketelrendement; ongeveer 10% gaat verloren via rookgas en andere ketelverliezen.',
      'HR-ketels lijken soms boven 100% te zitten omdat ze condensatiewarmte uit de rookgassen terugwinnen; dat is een rekentechnische vergelijking met de onderwaarde van gas, geen gratis energie.',
      'Warmtepompfactor 3 is hier een middenaanname voor de omzetting naar elektrische warmtevraag, juist omdat warmtepompen in de winter minder efficiënt zijn.',
      'In de gasvraag zit naast ruimteverwarming ook aardgas voor industrie; dat is kleiner, maar wordt met dezelfde factor omgerekend.',
      'De winter is het echte probleem: daar vallen vraag en piekbelasting samen en daalt de warmtepompefficiëntie.',
      'Warm water loopt het hele jaar door, en ook daar is de vraag of factor 3 altijd gehaald wordt.',
      'In dit scenario zijn geen warmtenetten voorzien, omdat die voor de eindgebruiker meestal economisch duurder zijn.',
      'Plus/min: moderne lucht-water-warmtepompen kunnen in werkelijkheid een SCOP van 5 of hoger halen.',
      'Plus/min: de industriële warmtevraag is onzeker; het is niet zeker dat factor 3 daar gehaald wordt.',
      'Plus/min: betere isolatie kan de warmtevraag met circa 10-20% verlagen, in orde van grootte ongeveer 3,8-7,5 TWh.',
    ],
    relatedAssumptionIds: ['balans-transport-ev-efficiency-factor', 'kritisch-2050-nulmeting'],
    tags: ['warmtevraag', 'gas', 'warmtepomp', 'hr-ketel', 'scop', 'industrie', 'isolatie', 'warmtenetten'],
  },
  {
    id: 'faq-heat-networks',
    question: 'Waarom gaat dit model niet uit van warmtenetten?',
    shortAnswer: 'Dit model gaat bewust niet uit van extra warmtenetten om een worst-case scenario voor de elektrische warmtevraag te hebben.',
    detailedAnswer: 'Het model rekent met een volledig elektrische warmtevoorziening via warmtepompen, zonder uitbreiding van warmtenetten. Dit is een bewuste scenariokeuze om de maximale belasting op het elektriciteitsnet in beeld te brengen. In de praktijk is de vraag of warmtenetten op grote schaal een rol gaan spelen.',
    detailedBullets: [
      'Warmtenetten zijn in de praktijk vrijwel altijd duurder dan een individuele warmtepomp voor de eindgebruiker.',
      'Warmtenetten zorgen voor een vendor lock-in: gebruikers kunnen niet vrij kiezen van leverancier of technologie te wisselen.',
      'Warmtenetten komen in Nederland moeizaam van de grond door hoge aanlegkosten, organisatorische complexiteit en gebrek aan schaal.',
      'Bij een warmtenet heeft de gebruiker geen voordeel van eigen PV-opwek, wat bij een warmtepomp wel het geval is.',
    ],
    relatedAssumptionIds: ['kritisch-2050-nulmeting'],
    tags: ['warmtenetten', 'warmtepomp', 'worst-case', 'elektrificatie', 'vendor lock-in', 'pv'],
  },
  {
    id: 'faq-winter-heat-profile-adjustment',
    question: 'Waarom is het winterprofiel voor verwarming aangepast?',
    shortAnswer: 'Het model corrigeert nu per dag alleen als de temperatuur ergens in die 24 uur onder 10°C komt; anders blijft het bronprofiel ongewijzigd.',
    detailedAnswer: 'De huidige versie gebruikt het werkelijke gasprofiel als basis en past alleen op koude dagen een lichte warmtepompcorrectie toe.',
    detailedBullets: [
      'We berekenen de warmtevraag op basis van het werkelijke gasverbruik.',
      'Dagregel: als de temperatuur in die 24 uur onder 10°C zakt, passen we een lichte correctie toe.',
      'Uitgangspunt: de warmtepomp draait continu en moduleert zelf het vermogen; bij correctie wordt het s nachts iets hoger en overdag iets lager.',
      'Als geen enkel uur onder 10°C komt, blijft het bronprofiel voor die dag intact.',
      'De dagsom blijft gelijk; alleen de verdeling binnen de dag verandert.',
    ],
    relatedAssumptionIds: ['kritisch-2050-nulmeting'],
    tags: ['winterprofiel', 'warmtepomp', 'nachtverlaging', 'temperatuur', 'modelaanname', 'uurprofiel'],
  },
  {
    id: 'faq-hot-water-gw',
    question: 'Hoeveel GW is nodig voor tapwater?',
    shortAnswer: 'Met een grove nationale rekensom kom je uit op ongeveer 2 GW thermisch continu, en na omzetting naar elektrisch circa 0,6 GW.',
    detailedAnswer: 'Indicatieve rekenlijn voor Nederland, bedoeld als orde-grootte en niet als exact netdimensioneringsgetal:',
    detailedBullets: [
      'Bronindicaties verbruik: CBS en Drinkwaterplatform noemen watergebruik rond 50 liter per persoon per dag en een totaalgebruik rond 120 liter per persoon per dag.',
      'Aannames voor warm water: ongeveer 41% warmwateraandeel, opwarming van 20°C naar 60°C (delta T = 40°C).',
      'Daarmee volgt voor Nederland een continue tapwaterwarmtevraag in orde-grootte van circa 2 GW thermisch.',
      'Omrekening naar elektrisch met modelaanname 0,9/3 (ketelrendement/warmtepompfactor): 2 x 0,9 / 3 = circa 0,6 GW elektrisch continu.',
      'In werkelijkheid varieert dit sterk per seizoen, gezinssamenstelling, gedrag, doucheduur, toestelrendement en leidingverliezen.',
      'Bronnen: https://www.cbs.nl/nl-nl/longread/aanvullende-statistische-diensten/2022/watergebruik-thuis--wgt---2021/4-totaal-watergebruik en https://www.drinkwaterplatform.nl/themas/waterbesparing/cijfers-waterverbruik/',
    ],
    relatedAssumptionIds: ['kritisch-2050-nulmeting'],
    tags: ['tapwater', 'warm water', 'gw', '0.6 gw', '2 gw', 'cbs', 'drinkwaterplatform'],
  },
  {
    id: 'faq-hot-water-profile-model-limit',
    question: 'Hoe gaat het model om met warmwaterprofielen (douchemomenten)?',
    shortAnswer: 'Het model volgt nu vooral het gasafgeleide profiel en modelleert nog niet apart hoe warmtepompboilers en warmtepompen warmwater slim bufferen en laden.',
    detailedAnswer: 'In zomers gasverbruik zie je vaak duidelijke douchemomenten rond de ochtend en avond. Als de temperatuur boven de 10 °C blijft zie je hoe de energie voor warmwater piekt om 7 uur \'s ochtends en 19-20 uur \'s avonds. Op zondagen ligt deze piek rond 10:00. Die pieken zijn in de praktijk bij warmtepompboilers en warmtepompen meestal vlakker, omdat het beschikbare vermogen lager is en de verwarmingsstrategie vaak anders werkt dan directe gasverbranding. Warmtepompen en warmtepompboilers hebben minder vermogen en zullen het verwarmen uitsmeren over langere tijd.',
    detailedBullets: [
      'Huidige beperking: geen aparte warmwatermodule voor warmtepompboilers/warmtepompen met buffervatsturing.',
      'Gasprofielen laten vaak scherpe pieken zien: doordeweeks rond 7:00 en 19:00-20:00, op zondag rond 10:00.',
      'Deze pieken zijn zichtbaar wanneer de buitentemperatuur boven 10 °C blijft (dan is er weinig ruimteverwarming).',
      'Bij warmtepompen worden deze pieken meestal uitgesmeerd over meer uren door lager vermogen en andere regelstrategie.',
      'Interpretatie: het huidige profiel is bruikbaar voor orde-grootte, maar kan warmwaterpieken in de zomer overschatten.',
    ],
    relatedAssumptionIds: ['kritisch-modelscope', 'kritisch-2050-nulmeting'],
    tags: ['warmwater', 'douche', 'zomerprofiel', 'warmtepompboiler', 'modelbeperking', 'piek', '7 uur', '19 uur', 'zondag'],
  },
  {
    id: 'faq-transport-kwh-calculation',
    question: 'Hoe is de benodigde kWh voor vervoer berekend?',
    shortAnswer: 'Alle niet-elektrische energiestromen onder vervoer uit CBS/NOVE zijn meegenomen en daarna omgerekend naar EV-elektra.',
    detailedAnswer: 'De vervoersvraag start vanuit brandstofgerelateerde vervoerdata die nog niet elektrisch is. Vervolgens wordt die fossiele eindenergie omgerekend naar benodigde elektrische energie op basis van een EV-efficiencyaanname. Daarmee ontstaat de elektrische kWh-reeks voor vervoer in het model.',
    relatedAssumptionIds: ['balans-transport-ev-efficiency-factor'],
    tags: ['vervoer', 'kwh', 'cbs', 'nove', 'berekening'],
  },
  {
    id: 'faq-electricity-profile-entso-visibility',
    question: 'Wat betekent het dat het elektriciteitsprofiel uit ENTSO/TenneT-data komt?',
    shortAnswer: 'Dit profiel volgt wat op netniveau zichtbaar is. Opwek en verbruik achter de meter vallen daar (deels) buiten.',
    detailedAnswer: 'Het gebruikte elektriciteitsprofiel komt uit ENTSO-data die aansluit op wat TenneT op netniveau ziet. Daardoor is dit geen volledige weergave van alle lokale energiestromen achter individuele meters.',
    detailedBullets: [
      'Achter-de-meter opwek en direct eigen gebruik zijn niet volledig zichtbaar in dit profiel.',
      'Lokale uitwisseling die TenneT niet als aparte netafname terugziet, verschijnt ook niet direct in de reeks.',
      'Praktisch: wat je buurman opwekt en direct lokaal gebruikt, zie je niet als apart verbruiksprofiel terug.',
      'Ook wat jij opwekt en je buurman lokaal verbruikt, is voor TenneT niet als aparte transactie zichtbaar; hoogstens als netto reststroom op hoger netniveau.',
      'Gebruik dit profiel dus als netzichtbare vraag/opwek, niet als complete registratie van alle lokale energiestromen.',
    ],
    relatedAssumptionIds: ['kritisch-modelscope', 'kritisch-2050-nulmeting'],
    tags: ['elektra', 'entso', 'tennet', 'achter de meter', 'netzicht', 'profiel'],
  },
  {
    id: 'faq-electricity-dunkelflaute-current-provisions',
    question: 'Hoe groot is het probleem bij dunkelflaute?',
    shortAnswer: 'In de simulatie van 2024 wekken zon en wind tijdens een dunkelflaute slechts ongeveer 8% van de vraag op. Zelfs met nieuwe windparken op zee blijft een tekort van 85-90% bestaan.',
    detailedAnswer: 'Tijdens een dunkelflaute-periode valt de opwek uit zon en wind vrijwel stil. In de 2024-simulatie komt slechts circa 8% van de gevraagde elektriciteit binnen uit zon en wind. Nieuwe windmolens op zee verbeteren dit doordat ze hoger zijn en meer wind vangen, en een lagere cut-off hebben (3 m/s in plaats van 4 m/s). Maar zelfs met deze nieuwe parken blijf je een tekort houden van ongeveer 85-90%.',
    detailedBullets: [
      'In de dunkelflaute wekken zon en wind ongeveer 8% op in de 2024-simulatie.',
      'Het is relatief warm door het wolkendek, waardoor het niet snel afkoelt. Als het wel helder weer is, heb je in de winter best nog veel zon die de tekorten beperkt.',
      'De simulatie gaat uit van de huidige windparken. Nieuwe windmolens op zee zijn hoger en vangen daardoor meer wind.',
      'Nieuwe windturbines hebben een lagere cut-off: 3 m/s in plaats van 4 m/s, waardoor ze minder snel helemaal terugvallen naar 0 output.',
      'Zelfs met de nieuw te bouwen windparken blijf je een tekort houden van ongeveer 85-90%.',
    ],
    relatedAssumptionIds: ['kritisch-modelscope'],
    tags: ['dunkelflaute', 'zon', 'wind', 'tekort', '8%', '15%', '85%', '90%', 'windturbines', 'cutoff', '3 m/s', '4 m/s', 'hogere luchtlagen'],
  },
  {
    id: 'faq-electricity-grid-congestion-model-scope',
    question: 'Houdt dit model rekening met netcongestie?',
    shortAnswer: 'Nee, netcongestie is in dit model niet expliciet doorgerekend. Daardoor kan de echte systeemdruk lokaal zwaarder zijn dan deze uitkomst suggereert.',
    detailedAnswer: 'In de huidige elektrificatie-scenariovergelijking stijgt de jaarvraag van ongeveer 121 TWh naar circa 180 TWh (ongeveer +49%), terwijl de winterpiek op 2025-profielen veel sterker oploopt van circa 19 GW naar ongeveer 33 GW. Dit model laat daarmee piekdruk wel zien, maar niet de volledige netcongestieproblematiek zoals die in andere studies vaak wordt gevonden.',
    detailedBullets: [
      'Jaarenergie groeit in dit kader beperkt: 121 -> 180 TWh (ongeveer +49%).',
      'Vermogenspiek groeit veel harder: circa 19 -> 33 GW op wintermomenten.',
      'Netcongestie wordt hier niet expliciet gemodelleerd (geen gedetailleerde regionale netbeperkingen).',
      'Grote extra systeemdruk ontstaat vooral wanneer ook grootschalige waterstofproductie wordt toegevoegd (orde-grootte ~333 TWh extra).',
      'Nuance: waterstofproductie gebeurt doorgaans in grootschalige clusters/centrales en niet als wijkvraag achter elke lokale aansluiting.',
    ],
    relatedAssumptionIds: ['kritisch-modelscope', 'kritisch-2050-nulmeting'],
    tags: ['netcongestie', 'elektra', '121 twh', '180 twh', '19 gw', '33 gw', 'waterstof', 'modelscope'],
  },
  {
    id: 'faq-grid-capacity-for-ev-charging',
    question: 'Kan het stroomnet vervoer wel aan als iedereen elektrisch gaat laden?',
    shortAnswer: 'De extra jaarvraag voor vervoer is in dit scenario relatief beperkt; de echte uitdaging zit vooral in gelijktijdigheid van laden, niet in de jaarenergie zelf.',
    detailedAnswer: 'Rekenlijn en interpretatie in het kort:',
    detailedBullets: [
      'Totale elektriciteitsvraag in deze redenering: circa 180 TWh/jaar.',
      'Vervoer daarin: circa 24 TWh/jaar, oftewel ongeveer 13,3% van het totaal.',
      'Gemiddeld vermogen vervoer: 24 TWh / 8760 uur = 2,74 GW.',
      'Per huishouden (8,2 mln): 24.000.000.000 kWh / 8.200.000 = 2.927 kWh/jaar.',
      'Dat is gemiddeld 0,334 kWh per uur per huishouden (ongeveer 334 W).',
      'Noot: de 24 TWh bevat alle vervoerssegmenten, inclusief zwaar vervoer en scheepvaart.',
      'Vertaling naar huishoudens is dus een grove bovengrens voor personenautoladen thuis.',
      'De netuitdaging zit vooral in gelijktijdig laden (bijvoorbeeld rond 17:00), niet in de jaarenergie zelf.',
      'Pieken kunnen worden gedempt met gespreid laden, lokale batterijen en slimme laadstrategieen.',
    ],
    relatedAssumptionIds: ['balans-transport-ev-efficiency-factor', 'balans-private-grid-limit'],
    tags: ['stroomnet', 'vervoer', 'laden', 'piek', '24 twh', '180 twh', 'per huishouden'],
  },
  {
    id: 'faq-v2g-modeling',
    question: 'Hoe heeft het model Vehicle-to-Grid (V2G) gemodelleerd?',
    shortAnswer: 'In de huidige versie doet het model nog niets met V2G; bidirectioneel laden van auto\'s naar het net is nog niet meegenomen.',
    detailedAnswer: 'V2G is een relevante optimalisatie voor netbelasting, maar nog geen actieve modelcomponent. Voor jaarverbruik verandert dit niet. Wel is de verwachting dat gebruikers dit inzetten om hun eigen batterijbuffer te vergroten of om ervoor te zorgen dat de auto altijd oplaadt bij PV-overschot.',
    relatedAssumptionIds: ['balans-v2g-not-modeled', 'balans-private-grid-limit'],
    tags: ['v2g', 'vehicle-to-grid', 'auto', 'pv overschot', 'netbelasting', 'eigen batterijbuffer'],
  },
  {
    id: 'faq-v2g-1twh-origin',
    question: 'Hoe groot is de V2G-batterijpotentie in 2050?',
    shortAnswer: 'Als vrijwel de hele wegvloot elektrisch is, ligt de orde-grootte rond 1,08 TWh (alleen personenauto\'s) tot circa 1,33 TWh (inclusief bestel- en vrachtauto\'s).',
    detailedAnswer: 'Indicatieve 2050-rekensom bij volledige elektrificatie van het wagenpark, met afgeronde vlootaantallen uit 2025 als proxy en 100 kWh per personen-/bestelauto en 500 kWh per vrachtauto:',
    detailedBullets: [
      'Alleen personenauto\'s: 10,8 mln x 100 kWh = 1,08 TWh',
      'Personenauto\'s + bestelauto\'s + vrachtauto\'s: (10,8 mln x 100) + (1,3 mln x 100) + (231,6k x 500) = circa 1,33 TWh',
      'Bron basisvloot: RDW Open Data (dataset m9d7-ebf2, categorieen M1/N1/N2+N3)',
    ],
    relatedAssumptionIds: ['balans-v2g-not-modeled'],
    tags: ['v2g', '2050', 'alles ev', '1.08 twh', '1.33 twh', '100 kwh', 'rdw', 'm9d7-ebf2'],
  },
  {
    id: 'faq-2050-baseline-expectations',
    question: 'Hoe gaat de site om met toekomstverwachtingen richting 2050?',
    shortAnswer: 'De site gebruikt een 2050-nulmeting als referentiescenario: gebaseerd op 2025-profielen die sterk geelektrificeerd worden.',
    detailedAnswer: 'We kiezen bewust voor een uitlegbaar referentiekader in plaats van een volledige toekomstvoorspelling. Daardoor kun je scenario\'s vergelijken zonder schijnnauwkeurigheid. De volgende factoren kunnen de uitkomst zowel positief als negatief beinvloeden en zijn daarom nu niet allemaal als losse plus/min-correctie doorgerekend:',
    detailedBullets: [
      'Bevolkingsgroei',
      'Groei van datacenters',
      'Efficientere apparatuur',
      'Verplaatsing of krimp van zware industrie',
      'Autodelen of autonoom vervoer',
      'Isolatieverbetering',
      'Betere batterijen',
      'Hogere opbrengst van zonnepanelen en gevel-PV',
    ],
    relatedAssumptionIds: ['kritisch-2050-nulmeting', 'kritisch-modelscope'],
    tags: ['2050', 'nulmeting', 'referentie', 'bevolkingsgroei', 'datacenters', 'isolatie', 'batterijen', 'zonnepanelen'],
  },
  {
    id: 'faq-2050-why-mostly-electric',
    question: 'Waarom rekent dit scenario richting 2050 met (bijna) alles elektrisch?',
    shortAnswer: 'Dat is een pragmatische scenario-keuze: niet omdat echt alles elektrisch zal zijn, maar omdat kostenprikkels en beleid de elektrificatie sterk duwen.',
    detailedAnswer: 'In werkelijkheid zal waarschijnlijk niet 100% elektrisch zijn. Voor dit referentiescenario kiezen we "bijna alles elektrisch" om een duidelijke bovengrens en vergelijkbaar rekenkader te hebben. Redenen zijn vooral economisch en beleidsmatig:',
    detailedBullets: [
      'Elektrisch rijden is per kilometer vaak goedkoper dan fossiel rijden.',
      'Batterijprijzen dalen naar verwachting verder.',
      'PV-gebruikers kunnen een groot deel van het jaar op eigen overschot laden.',
      'Overheidssturing (normen, beprijzing, infrastructuur) versnelt elektrificatie.',
    ],
    relatedAssumptionIds: ['balans-transport-ev-efficiency-factor', 'kritisch-2050-nulmeting'],
    tags: ['2050', 'elektrificatie', 'kosten', 'beleid', 'pv overschot', '20.000 km', '3.75 km/kwh', 'besparing'],
  },
  {
    id: 'faq-kosten-bev-vs-benzine',
    question: 'Kosten BEV vs benzine: wat is een logische voorbeeldberekening?',
    shortAnswer: 'BEV is in gebruik vaak goedkoper per km, maar de aanschaf is nu nog hoger. Met 20.000 km/jaar komt de totale voorbeeldbesparing over 10 jaar grofweg uit op enkele tienduizenden euro’s.',
    detailedAnswer: 'Voorbeeld met transparante aannames en een vergelijking van km-prijzen, onderhoud en aanschaf:',
    detailedBullets: [
      'Jaarafstand: 20.000 km.',
      'Aannames benzine: 1 op 15 en 2,10 EUR/l -> benzine-km-prijs = 2,10 / 15 = 0,140 EUR/km.',
      'Aannames stroom: 0,25 EUR/kWh en 50% laden via eigen PV-overschot -> effectieve stroomprijs = 0,125 EUR/kWh.',
      'Afleiding EV km/kWh vanuit factor 3,75: bij benzine 15 km/l en 8,9 kWh/l geeft dit (15 x 3,75) / 8,9 = 6,32 km/kWh.',
      'BEV-km-prijs = 0,125 / 6,32 = 0,020 EUR/km.',
      'Verschil per km = 0,140 - 0,020 = 0,120 EUR/km.',
      'Jaarlijkse energiebesparing = 20.000 x 0,120 = circa 2.400 EUR/jaar.',
      '10-jaars energiebesparing = circa 24.000 EUR (zonder discontering).',
      'Onderhoud is meestal lager bij BEV: een verbrandingsmotor heeft duizenden onderdelen, een elektromotor slechts tientallen; daardoor vallen onderhouds- en slijtagekosten vaak lager uit.',
      'De aanschafprijs van BEV is nu vaak nog hoger, maar die kan verder dalen door goedkopere batterijen.',
      'Totale kostenbesparing over 10 jaar hangt dus af van energiekosten, onderhoud, aanschafprijs, restwaarde en financiering.',
    ],
    relatedAssumptionIds: ['balans-transport-ev-efficiency-factor', 'kosten-battery-cell-price-default'],
    tags: ['kosten bev', 'benzine', 'km-prijs', '20.000 km', '3.75', 'pv overschot', 'onderhoud', '10 jaar'],
  },
  {
    id: 'faq-balance-dispatch-explained',
    question: 'Waarom is publiek + privé overschot groter dan de jaarbalans?',
    shortAnswer: 'De jaarbalans is het netto resultaat (overschot − tekort). Publiek + privé overschot is de totale curtailment in alle overschot-uren samen. Het verschil is het tekort.',
    detailedAnswer: 'De jaarbalans telt álle uren bij elkaar op: overschot-uren (positief) minus tekort-uren (negatief). Het publiek en privé aandeel zijn alleen de curtailment in overschot-uren. Het tekort (bv. 29,6 TWh in een scenario zonder batterij) wordt afgetrokken. Rekenvoorbeeld: (Publiek 78,2 + Privé 57,5) − Tekort 29,6 = Jaarbalans 106,1.',
    detailedBullets: [
      'Jaarbalans = opwek minus vraag over alle uren (netto resultaat).',
      'Overschot totaal = publiek + privé curtailment in overschot-uren (bruto overschot).',
      'Het verschil is het tekort: ongedekte vraag in tekort-uren.',
      'Zonder batterij is de netto balans gelijk aan de jaarbalans.',
      'Met batterij kan de netto balans afwijken doordat opgeslagen energie later wordt gebruikt.',
    ],
    relatedAssumptionIds: ['balans-private-grid-limit', 'kritisch-modelscope'],
    tags: ['balans', 'dispatch', 'publiek overschot', 'prive overschot', '70%', '30%', 'bruto', 'netto', 'curtailment'],
  },
  {
    id: 'faq-why-public-private-split',
    question: 'Waarvoor is een verdeling van publiek en prive voor zonnepanelen en batterij nodig',
    shortAnswer: 'Om te modelleren wat er achter de meter gebeurt bij partijen met eigen zonnepanelen en batterijen.',
    detailedAnswer: '',
    detailedBullets: [
      'Als niet iedereen voldoende heeft aan eigen opwek hou je een vraag op het publieke net.',
      'Eigenaars van PV en batterijen zullen eerst hun teveel opslaan in batterijen voordat ze het verkopen aan het publieke net.',
      'In 2050-scenario\'s: 70% (bijna iedereen heeft PV en batterijen)',
      'Instelbaar via de slider op de balanspagina',
    ],
    relatedAssumptionIds: ['kritisch-modelscope'],
    tags: ['publiek', 'privaat', '35%', '70%', 'achter de meter', 'huishoudens', 'bedrijven', 'PV'],
  },
  {
    id: 'faq-why-private-grid-limit',
    question: 'Waarom zit er een limiet op hoeveel privaat uit het publieke net mag halen?',
    shortAnswer: 'De limiet modelleert netcongestie: de fysieke infrastructuur kan niet onbeperkt vermogen transporteren van publieke opwek naar private verbruikers.',
    detailedAnswer: 'Het elektriciteitsnet heeft fysieke grenzen. Transformatoren, kabels en verdeelstations kunnen maar een bepaalde hoeveelheid vermogen aan. Als alle huishoudens tegelijk stroom zouden trekken uit het publieke net, zou de infrastructuur overbelast raken. De standaard 35 GW is een realistische bovengrens voor het Nederlandse distributienet. Zonder deze limiet zou het model suggereren dat private tekorten altijd volledig uit publieke opwek gedekt kunnen worden — wat in de praktijk niet kan.',
    detailedBullets: [
      'Netcongestie is een reëel probleem in Nederland',
      'De 35 GW bovengrens voorkomt onrealistische piekbelasting op het distributienet',
      'In de praktijk worden netverzwaringen uitgevoerd, maar die kosten tijd en geld',
      'Instelbaar via \'Max. private netbelasting\' in de balansinstellingen',
    ],
    relatedAssumptionIds: ['balans-private-grid-limit'],
    tags: ['netcongestie', '35 gw', 'private netlimiet', 'netbelasting', 'distributienet'],
  },
  {
    id: 'faq-why-seasonal-reserve',
    question: 'Hoe werkt de dynamische private reserve met 14 dagen vooruitkijken?',
    shortAnswer: 'Het model rekent een lopende tekortbehoefte in de komende 14 dagen en hanteert tegelijk een zachte ondergrens van 20% SoC.',
    detailedAnswer: 'Voor elk uur wordt in een 14-daags venster achterwaarts gerekend: tekorturen verhogen de benodigde SoC, overschoturen verlagen die weer doordat je dan kunt laden. De batterij probeert daarbij minimaal 20% te behouden, zodat de sturing minder perfect-vooruitziend wordt en er een praktische buffer blijft.',
    detailedBullets: [
      'Horizon: 14 dagen (336 uur) vooruitkijken per uur.',
      'Achterwaarts rekenen: tekorten tellen op, laadkansen in overschoturen trekken de behoefte weer omlaag.',
      'Doel-SoC per uur = max(20% buffer, berekende tekortbehoefte).',
      'Bij tekort gebruikt privaat eerst de eigen batterij en pas daarna het publieke net.',
    ],
    relatedAssumptionIds: ['balans-private-winter-reserve'],
    tags: ['dynamische reserve', '14 dagen', '20%', 'tekortbehoefte', 'batterij', 'balans'],
  },
  {
    id: 'faq-why-24h-lookahead',
    question: 'Waarom gebruikt de simulatie geen 24-uurs private exportreserve meer?',
    shortAnswer: 'De 24-uurs exportreserve is vervangen door één 14-daagse strategie die direct op toekomstige tekorturen stuurt.',
    detailedAnswer: 'In de nieuwe aanpak wordt niet apart bepaald hoeveel export veilig is op basis van 24 uur. In plaats daarvan volgt de private batterij één regelset met een 14-daags venster: tekortbehoefte opbouwen, overschoturen benutten om zo laat mogelijk te laden, en bij actuele tekorten eerst ontladen.',
    detailedBullets: [
      'Geen aparte 24-uurs exportrem meer als hoofdsturing.',
      'Eén uniforme private dispatchstrategie voor alle uren.',
      'Laadkansen in overschoturen worden gebruikt om latere tekorten af te dekken.',
      'Bij tekort: eerst private batterij, daarna publiek net.',
    ],
    relatedAssumptionIds: ['balans-private-winter-reserve'],
    tags: ['14 dagen', 'private strategie', 'export', 'batterij', 'tekort'],
  },
  {
    id: 'faq-why-convergence-loop',
    question: 'Waarom draait de simulatie maximaal 5 iteraties?',
    shortAnswer: 'De batterij aan het eind van het jaar moet dezelfde lading hebben als aan het begin, anders is de jaarbalans niet sluitend.',
    detailedAnswer: 'Een batterijsimulatie over een heel jaar is een circulair probleem: de eindtoestand van 31 december is de begintoestand van 1 januari. De simulatie start met 50% lading en draait het jaar door. Vervolgens wordt de eindlading als nieuwe beginlading gebruikt. Dit herhaalt zich totdat begin en eind vrijwel gelijk zijn (minder dan 1 kWh verschil). Meestal is dat na 2-3 iteraties; de maximale 5 voorkomt oneindig loopen bij instabiele configuraties.',
    detailedBullets: [
      'Start: beide batterijen op 50%',
      'Elke iteratie: eind-SoC wordt nieuwe begin-SoC',
      'Stopt als verschil < 1 kWh, of na maximaal 5 iteraties',
      'Zorgt voor een sluitende jaarbalans zonder kunstmatige begin- of eindcorrecties',
    ],
    relatedAssumptionIds: ['kritisch-modelscope'],
    tags: ['convergentie', 'iteratie', 'batterij', 'simulatie', 'jaarbalans'],
  },
  {
    id: 'faq-infra-cost-split',
    question: 'Hoe worden infrastructuurkosten verdeeld tussen huishoudens en bedrijven?',
    shortAnswer: 'Volgens de CBS Energiebalans: 35% huishoudens, 65% bedrijven. De vaste infra-kosten (TenneT + publieke batterij) worden naar rato over deze groepen verdeeld.',
    detailedAnswer: 'Nederland heeft circa 8,2 miljoen huishoudens en 800.000 zakelijke aansluitingen. De CBS Energiebalans laat zien dat huishoudens ongeveer 35% van de totale elektriciteit verbruiken. De infrastructuurkosten (TenneT-net, aanlandingssystemen, publieke batterij) worden volgens deze 35/65-verdeelsleutel toegerekend. Voor huishoudens komt daar nog 21% BTW bovenop; bedrijven verrekenen de BTW.',
    detailedBullets: [
      'CBS Energiebalans: huishoudens verbruiken ~35% van totaal elektriciteitsverbruik',
      '8,2 mln huishoudens × 0,35 aandeel = vaste infra-kosten per huishouden per maand',
      '800.000 zakelijke aansluitingen × 0,65 aandeel = vaste infra-kosten per bedrijf per maand',
      'Huishoudens betalen 21% BTW over infra; bedrijven verrekenen BTW',
      'Energiebelasting verschilt: huishoudens 12,6 ct/kWh (eerste schijf), bedrijven 5,3 ct/kWh',
      'Het gemiddelde huishouden verbruikt in dit model ca. 3.500–5.000 kWh/jaar afhankelijk van het scenario',
    ],
    relatedAssumptionIds: ['kosten-household-share', 'kosten-household-variable-price'],
    tags: ['infrastructuur', '35%', '65%', 'huishoudens', 'bedrijven', 'CBS', 'energiebalans', 'TenneT', 'BTW', 'energiebelasting'],
  },
  {
    id: 'faq-transport-ev-factor-375',
    question: 'Waarom is EV 3,75 keer zo efficiënt in dit model?',
    shortAnswer: 'Dit is een pragmatische middenaanname uit vergelijking van km/liter benzine met km/kWh van moderne auto\'s, waar grofweg factor 4 uitkomt.',
    detailedAnswer: 'Waarom 3,75 als werkfactor in plaats van exact 4,0:',
    detailedBullets: [
      'Voor personenauto\'s ligt de vergelijking verbrandingsauto versus EV vaak rond factor 4.',
      'Het model kiest 3,75 als pragmatische middenwaarde om niet te agressief te rekenen.',
      'Zwaar vervoer kan lager uitvallen dan factor 4.',
      'Vervanging van oudere, minder efficiente voertuigen door nieuwe EV\'s kan juist boven factor 4 uitkomen.',
    ],
    relatedAssumptionIds: ['balans-transport-ev-efficiency-factor'],
    tags: ['vervoer', 'ev', '3.75', 'efficientie', 'factor 4', 'zwaar vervoer'],
  },
  {
    id: 'faq-curtailment-priority-order',
    question: 'Hoe werkt curtailment en waarom in die volgorde?',
    shortAnswer: 'Curtailment is het afschakelen van opwek als er meer stroom is dan vraag en batterijen vol zijn. De volgorde: windland → windzee → zon → kern (tot 50%) → afval/biogas.',
    detailedAnswer: 'Als batterijen vol zijn en er nog overschot is, moet opwek worden teruggeregeld. De volgorde is een afweging tussen technische regelbaarheid en economische logica. Er zijn twee tegengestelde redeneringen mogelijk:',
    detailedBullets: [
      'Huidige volgorde (technisch): wind eerst — turbines kunnen snel worden stilgezet door de bladen uit de wind te draaien. Veel kleine eenheden = fijnmazig regelbaar.',
      '1. Windland — snelst regelbaar, veel turbines, bladen uit de wind = direct minder productie.',
      '2. Windzee — duurdere bouw, hogere capaciteitsfactor, dus iets waardevoller om te laten draaien.',
      '3. Publieke zon — PV per omvormer af te schakelen. Overdag is er vaak toch al overschot.',
      '4. Kernenergie — max 50% terug. Ontworpen voor continu bedrijf; rampen is duur en technisch beperkt.',
      '5. Afval/biogas — vaste basislast 300 MW, continu proces, nauwelijks stil te zetten.',
      '',
      'Deze volgorde is zowel technisch als economisch logisch:',
      '• Wind stilzetten bespaart OPEX (minder slijtage aan draaiende delen zoals lagers en tandwielen). De totale systeemkosten dalen, dus de prijs per nuttige kWh wordt lager.',
      '• Zon stilzetten bespaart niets — PV heeft geen bewegende delen en vrijwel geen variabele kosten. Daarom draait zon door zolang het kan.',
      '• Kern en afval/biogas komen als laatste omdat die óf technisch niet zomaar stil kunnen, óf als continue basislast functioneren.',
      '• Na publieke curtailment gaat resterend overschot naar waterstof (indien actief).',
    ],
    relatedAssumptionIds: ['balans-private-winter-reserve'],
    tags: ['curtailment', 'volgorde', 'windland', 'windzee', 'zon', 'kernenergie', 'afval', 'biogas', 'afschakelen', 'overschot', 'OPEX'],
  },
  {
    id: 'faq-why-high-kwh-price',
    question: 'Waarom is de prijs per kWh zo hoog?',
    shortAnswer: 'Omdat private zon en batterijen in de zomer zorgen voor enorme publieke curtailment. De weinige kWh die publiek wél levert, moeten de volledige investeringskosten dragen.',
    detailedAnswer: 'Het probleem zit in de zomer. Private zonnepanelen en batterijen dekken dan een groot deel van de vraag. Het publieke net produceert volop (wind, kern) maar kan die stroom niet kwijt — er is geen vraag en de batterijen zijn vol. Resultaat: massale curtailment van publieke opwek. De totale publieke investering (capex + opex van windparken, kerncentrales, netinfra) blijft gelijk, maar wordt terugverdiend over veel minder nuttig geleverde kWh. Daardoor stijgt de prijs per kWh.',
    detailedBullets: [
      'In de zomer: private PV + batterij dekt eigen vraag → publiek overschot wordt gecurtailed.',
      'Publieke opwek draait door maar kan niet worden afgezet → hoge curtailment.',
      'Totale publieke kosten (capex wind, kern, TenneT) veranderen niet.',
      'Die vaste kosten worden verdeeld over minder nuttig geleverde publieke kWh.',
      'Gevolg: prijs per kWh stijgt.',
      'Zonder private PV zouden dezelfde publieke centrales méér kWh kwijt kunnen → lagere prijs per kWh.',
      'Dit is het dilemma van elektrificatie: hoe meer private opwek, hoe duurder de publieke kWh.',
    ],
    relatedAssumptionIds: ['kosten-household-share', 'kosten-household-variable-price'],
    tags: ['prijs', 'kWh', 'curtailment', 'publiek', 'privaat', 'zon', 'batterij', 'zomer', 'investering'],
  },
];
